CREATE TABLE `example_table` (
  `id` INT64,
  `bigint_column` INTEGER,
  `byteint_column` BYTEINT,
  `decimal_column` DECIMAL,
  `numeric_column` NUMERIC,
  `float_column` FLOAT,
  `real_column` REAL,
  `double_column` DOUBLE,
  `char_column` CHAR(10),
  `nchar_column` NCHAR(20),
  `nvarchar_column` NVARCHAR(50),
  `varbinary_column` VARBINARY(100),
  `st_geometry_column` ST_GEOMETRY,
  `boolean_column` BOOL,
  `date_column` DATE,
  `time_column` TIME,
  `timetz_column` TIMETZ,
  `timestamp_column` DATETIME
)